### ISSUE TITLE
Responsible collumn confusion

### ISSUE THREAD

**Issue by volcov** [leomilrib/junkie#17]
When a pull request has Assignee, in junkie it is not easy to know if that person is the author or the assignee

junkie:

![screenshot from 2018-06-13 17-11-07](https://user-images.githubusercontent.com/345921/41375592-eccb7862-6f2c-11e8-902c-bde6eba8c8d2.png)

Github:

![screenshot from 2018-06-13 17-11-57](https://user-images.githubusercontent.com/345921/41375613-fbe76ebe-6f2c-11e8-9881-9ccbb05ae02a.png)

**Comment by leomilrib** [comment]
sorry for the delay.

yeah, I understood it now, let's clarify how the column works:
- If no one is assigned to the PR, that meas that the responsible one for it should be the User who opened it;
- If some other user is assigned to the PR, this User turns into the one responsible for the PR.

So the idea here is more _"who is gonna continue this work?"_ and not _"who should reviewed this PR?"_.

I'm considering adding different sections to the app to show first the PRs you were asked to review, cuz they should have a higher priority over the others from the organization.

Thanks for the feedback and feel free to contact me with any other doubts, questions and suggestions.
(sorry again for the delay :sweat_smile:)

See ya! :wave:
